### ISSUE TITLE
Error in .editorconfig file?

### ISSUE THREAD

**Issue by occupant** [UBCCM/ubc-clf8#15]
I must have glossed right over this, but I don't think this is correct:

```
indent_style = tab
indent_size = 4
```

I think it should be either:
```
indent_style = space
indent_size = 4
``` 

or just:
```
indent_style = tab
```

**Comment by richardtape** [comment]
No, I think this is fine.

As per https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties , `indent_size` can be an integer (as we have) or 'tab'. `tab_width` defaults to the value of `indent_size` if `indent_size` is an integer.

So for our setup, `tab_width` is defaulting to 4 (As we'd want) because `indent_size` is an integer.

**Comment by occupant** [comment]
The error I was getting on compile was due to the sass-lint rules. I've adjusted them to be in line with the editorconfig rules and it's all good now. :)
